"""sprint_1_1_institucional

Revision ID: 929c75e84a3f
Revises: 0001
Create Date: 2026-05-13 13:12:47.719795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '929c75e84a3f'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unidades_autorizadoras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('origem_unidade', sa.Enum('SIAPE', 'SIORG', name='origemunidade'), nullable=False),
    sa.Column('cod_unidade_autorizadora', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=False),
    sa.Column('pgd_autorizado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unidades_autorizadoras')),
    sa.UniqueConstraint('origem_unidade', 'cod_unidade_autorizadora', name='uq_unidades_autorizadoras_origem_cod')
    )
    op.create_table('atos_autorizacao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unidade_autorizadora_id', sa.UUID(), nullable=False),
    sa.Column('autoridade', sa.String(length=255), nullable=False),
    sa.Column('data_publicacao', sa.Date(), nullable=False),
    sa.Column('referencia', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'SUSPENSO', 'REVOGADO', name='statusato'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unidade_autorizadora_id'], ['unidades_autorizadoras.id'], name=op.f('fk_atos_autorizacao_unidade_autorizadora_id_unidades_autorizadoras'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_atos_autorizacao'))
    )
    op.create_table('unidades_instituidoras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unidade_autorizadora_id', sa.UUID(), nullable=False),
    sa.Column('cod_unidade_instituidora', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=False),
    sa.Column('ato_instituicao_ref', sa.String(length=255), nullable=False),
    sa.Column('data_instituicao', sa.Date(), nullable=False),
    sa.Column('tipos_atividades', sa.Text(), nullable=False),
    sa.Column('modalidades_autorizadas', sa.JSON(), nullable=False),
    sa.Column('vagas_percentual_presencial', sa.Integer(), nullable=True),
    sa.Column('vagas_percentual_tt_parcial', sa.Integer(), nullable=True),
    sa.Column('vagas_percentual_tt_integral', sa.Integer(), nullable=True),
    sa.Column('vagas_percentual_tt_exterior', sa.Integer(), nullable=True),
    sa.Column('conteudo_minimo_tcr', sa.Text(), nullable=False),
    sa.Column('prazo_antecedencia_convocacao_dias', sa.Integer(), nullable=False),
    sa.Column('nivel_produtividade_adicional_tt', sa.Text(), nullable=True),
    sa.Column('vedacoes_participacao', sa.Text(), nullable=True),
    sa.Column('criterios_selecao_adicionais', sa.Text(), nullable=True),
    sa.Column('procedimento_registro_comparecimento', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('EM_VIGOR', 'SUSPENSO', 'REVOGADO', name='statuspgd'), nullable=False),
    sa.Column('data_suspensao_revogacao', sa.Date(), nullable=True),
    sa.Column('motivo_suspensao_revogacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unidade_autorizadora_id'], ['unidades_autorizadoras.id'], name=op.f('fk_unidades_instituidoras_unidade_autorizadora_id_unidades_autorizadoras'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unidades_instituidoras'))
    )
    op.create_table('unidades_execucao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unidade_instituidora_id', sa.UUID(), nullable=False),
    sa.Column('cod_unidade_executora', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=False),
    sa.Column('chefia_user_id', sa.Integer(), nullable=True),
    sa.Column('nivel_superior_user_id', sa.Integer(), nullable=True),
    sa.Column('coincide_com_instituidora', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chefia_user_id'], ['users.id'], name=op.f('fk_unidades_execucao_chefia_user_id_users')),
    sa.ForeignKeyConstraint(['nivel_superior_user_id'], ['users.id'], name=op.f('fk_unidades_execucao_nivel_superior_user_id_users')),
    sa.ForeignKeyConstraint(['unidade_instituidora_id'], ['unidades_instituidoras.id'], name=op.f('fk_unidades_execucao_unidade_instituidora_id_unidades_instituidoras'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unidades_execucao'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unidades_execucao')
    op.drop_table('unidades_instituidoras')
    op.drop_table('atos_autorizacao')
    op.drop_table('unidades_autorizadoras')
    # ### end Alembic commands ###
