"""initial schema

Revision ID: 213398d03375
Revises: 
Create Date: 2026-05-15 10:51:46.371111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '213398d03375'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='auditaction'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_record_id'), 'audit_logs', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_table_name'), 'audit_logs', ['table_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('registros_envio_api',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo_entidade', sa.Enum('PARTICIPANTE', 'PLANO_ENTREGAS', 'PLANO_TRABALHO', name='tipoentidadesync'), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('tentativa', sa.Integer(), nullable=False),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('erro_mensagem', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registros_envio_api'))
    )
    op.create_index(op.f('ix_registros_envio_api_entidade_id'), 'registros_envio_api', ['entidade_id'], unique=False)
    op.create_table('unidades_autorizadoras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('origem_unidade', sa.Enum('SIAPE', 'SIORG', name='origemunidade'), nullable=False),
    sa.Column('cod_unidade_autorizadora', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=False),
    sa.Column('pgd_autorizado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unidades_autorizadoras')),
    sa.UniqueConstraint('origem_unidade', 'cod_unidade_autorizadora', name='uq_unidades_autorizadoras_origem_cod')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'GESTOR_UNIDADE', 'CHEFE_IMEDIATO', 'SERVIDOR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('oauth_sub', sa.String(length=255), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cod_unidade_autorizadora', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('oauth_sub', name=op.f('uq_users_oauth_sub'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('atos_autorizacao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unidade_autorizadora_id', sa.UUID(), nullable=False),
    sa.Column('autoridade', sa.String(length=255), nullable=False),
    sa.Column('data_publicacao', sa.Date(), nullable=False),
    sa.Column('referencia', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'SUSPENSO', 'REVOGADO', name='statusato'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unidade_autorizadora_id'], ['unidades_autorizadoras.id'], name=op.f('fk_atos_autorizacao_unidade_autorizadora_id_unidades_autorizadoras'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_atos_autorizacao'))
    )
    op.create_table('notificacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo_evento', sa.Enum('AVALIACAO_REALIZADA', 'RECURSO_ABERTO', 'RECURSO_DECIDIDO', 'PRAZO_REGISTRO_IMINENTE', 'CONVOCACAO_EMITIDA', 'DESLIGAMENTO_REGISTRADO', 'PGD_SUSPENSO_REVOGADO', 'PLANO_APROVADO', name='tipoevento'), nullable=False),
    sa.Column('destinatario_user_id', sa.Integer(), nullable=True),
    sa.Column('destinatario_email', sa.String(length=255), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('contexto', sa.JSON(), nullable=True),
    sa.Column('enviada', sa.Boolean(), nullable=False),
    sa.Column('enviada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destinatario_user_id'], ['users.id'], name=op.f('fk_notificacoes_destinatario_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notificacoes'))
    )
    op.create_table('unidades_instituidoras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unidade_autorizadora_id', sa.UUID(), nullable=False),
    sa.Column('cod_unidade_instituidora', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=False),
    sa.Column('ato_instituicao_ref', sa.String(length=255), nullable=False),
    sa.Column('data_instituicao', sa.Date(), nullable=False),
    sa.Column('tipos_atividades', sa.Text(), nullable=False),
    sa.Column('modalidades_autorizadas', sa.JSON(), nullable=False),
    sa.Column('vagas_percentual_presencial', sa.Integer(), nullable=True),
    sa.Column('vagas_percentual_tt_parcial', sa.Integer(), nullable=True),
    sa.Column('vagas_percentual_tt_integral', sa.Integer(), nullable=True),
    sa.Column('vagas_percentual_tt_exterior', sa.Integer(), nullable=True),
    sa.Column('conteudo_minimo_tcr', sa.Text(), nullable=False),
    sa.Column('prazo_antecedencia_convocacao_dias', sa.Integer(), nullable=False),
    sa.Column('nivel_produtividade_adicional_tt', sa.Text(), nullable=True),
    sa.Column('vedacoes_participacao', sa.Text(), nullable=True),
    sa.Column('criterios_selecao_adicionais', sa.Text(), nullable=True),
    sa.Column('escala_customizada_mapeamento', sa.JSON(), nullable=True),
    sa.Column('procedimento_registro_comparecimento', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('EM_VIGOR', 'SUSPENSO', 'REVOGADO', name='statuspgd'), nullable=False),
    sa.Column('data_suspensao_revogacao', sa.Date(), nullable=True),
    sa.Column('motivo_suspensao_revogacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unidade_autorizadora_id'], ['unidades_autorizadoras.id'], name=op.f('fk_unidades_instituidoras_unidade_autorizadora_id_unidades_autorizadoras'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unidades_instituidoras'))
    )
    op.create_table('unidades_execucao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unidade_instituidora_id', sa.UUID(), nullable=False),
    sa.Column('cod_unidade_executora', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=False),
    sa.Column('chefia_user_id', sa.Integer(), nullable=True),
    sa.Column('nivel_superior_user_id', sa.Integer(), nullable=True),
    sa.Column('coincide_com_instituidora', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chefia_user_id'], ['users.id'], name=op.f('fk_unidades_execucao_chefia_user_id_users')),
    sa.ForeignKeyConstraint(['nivel_superior_user_id'], ['users.id'], name=op.f('fk_unidades_execucao_nivel_superior_user_id_users')),
    sa.ForeignKeyConstraint(['unidade_instituidora_id'], ['unidades_instituidoras.id'], name=op.f('fk_unidades_execucao_unidade_instituidora_id_unidades_instituidoras'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unidades_execucao'))
    )
    op.create_table('delegacoes_competencia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delegante_user_id', sa.Integer(), nullable=False),
    sa.Column('delegatario_user_id', sa.Integer(), nullable=False),
    sa.Column('competencia', sa.Enum('APROVAR_PLANO_ENTREGAS', 'REALIZAR_SELECAO', 'AVALIAR_REGISTROS', name='competencia'), nullable=False),
    sa.Column('unidade_execucao_id', sa.UUID(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delegante_user_id'], ['users.id'], name=op.f('fk_delegacoes_competencia_delegante_user_id_users')),
    sa.ForeignKeyConstraint(['delegatario_user_id'], ['users.id'], name=op.f('fk_delegacoes_competencia_delegatario_user_id_users')),
    sa.ForeignKeyConstraint(['unidade_execucao_id'], ['unidades_execucao.id'], name=op.f('fk_delegacoes_competencia_unidade_execucao_id_unidades_execucao'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delegacoes_competencia'))
    )
    op.create_table('participantes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('origem_unidade', sa.Enum('SIAPE', 'SIORG', name='origemunidade'), nullable=False),
    sa.Column('cod_unidade_autorizadora', sa.BigInteger(), nullable=False),
    sa.Column('cod_unidade_lotacao', sa.BigInteger(), nullable=False),
    sa.Column('matricula_siape', sa.String(length=7), nullable=False),
    sa.Column('cod_unidade_instituidora', sa.BigInteger(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('situacao', sa.Integer(), nullable=False),
    sa.Column('modalidade_execucao', sa.Integer(), nullable=False),
    sa.Column('data_assinatura_tcr', sa.Date(), nullable=False),
    sa.Column('api_sincronizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_ingresso_pgd', sa.Date(), nullable=True),
    sa.Column('data_desligamento', sa.Date(), nullable=True),
    sa.Column('motivo_desligamento', sa.Enum('A_PEDIDO', 'INTERESSE_ADMINISTRACAO', 'MUDANCA_UNIDADE', 'PGD_REVOGADO', name='motivodesligamento'), nullable=True),
    sa.Column('cumpriu_estagio_probatorio', sa.Boolean(), nullable=True),
    sa.Column('data_fim_estagio_probatorio', sa.Date(), nullable=True),
    sa.Column('tipo_vinculo', sa.Enum('EFETIVO', 'COMISSIONADO', 'EMPREGADO_PUBLICO', 'CONTRATO_DETERMINADO', 'ESTAGIARIO', name='tipovinculo'), nullable=False),
    sa.Column('acumula_cargos', sa.Boolean(), nullable=False),
    sa.Column('sujeito_adicional_ocupacional', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('unidade_execucao_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unidade_execucao_id'], ['unidades_execucao.id'], name=op.f('fk_participantes_unidade_execucao_id_unidades_execucao'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_participantes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participantes')),
    sa.UniqueConstraint('origem_unidade', 'cod_unidade_autorizadora', 'cod_unidade_lotacao', 'matricula_siape', name='uq_participante_api_key')
    )
    op.create_table('planos_entregas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_plano_entregas', sa.String(length=50), nullable=False),
    sa.Column('origem_unidade', sa.Enum('SIAPE', 'SIORG', name='origemunidade'), nullable=False),
    sa.Column('cod_unidade_autorizadora', sa.BigInteger(), nullable=False),
    sa.Column('cod_unidade_instituidora', sa.BigInteger(), nullable=False),
    sa.Column('cod_unidade_executora', sa.BigInteger(), nullable=False),
    sa.Column('unidade_execucao_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_termino', sa.Date(), nullable=False),
    sa.Column('avaliacao', sa.Integer(), nullable=True),
    sa.Column('data_avaliacao', sa.Date(), nullable=True),
    sa.Column('avaliado_por_user_id', sa.Integer(), nullable=True),
    sa.Column('aprovado_por_user_id', sa.Integer(), nullable=True),
    sa.Column('data_aprovacao', sa.Date(), nullable=True),
    sa.Column('ajustes_comunicados_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_sincronizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aprovado_por_user_id'], ['users.id'], name=op.f('fk_planos_entregas_aprovado_por_user_id_users')),
    sa.ForeignKeyConstraint(['avaliado_por_user_id'], ['users.id'], name=op.f('fk_planos_entregas_avaliado_por_user_id_users')),
    sa.ForeignKeyConstraint(['unidade_execucao_id'], ['unidades_execucao.id'], name=op.f('fk_planos_entregas_unidade_execucao_id_unidades_execucao'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planos_entregas')),
    sa.UniqueConstraint('origem_unidade', 'cod_unidade_autorizadora', 'id_plano_entregas', name='uq_plano_entregas_api_key')
    )
    op.create_table('processos_selecao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unidade_execucao_id', sa.UUID(), nullable=False),
    sa.Column('criterios_tecnicos', sa.Text(), nullable=False),
    sa.Column('n_vagas', sa.Integer(), nullable=False),
    sa.Column('resultado', sa.JSON(), nullable=False),
    sa.Column('realizado_por_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['realizado_por_user_id'], ['users.id'], name=op.f('fk_processos_selecao_realizado_por_user_id_users')),
    sa.ForeignKeyConstraint(['unidade_execucao_id'], ['unidades_execucao.id'], name=op.f('fk_processos_selecao_unidade_execucao_id_unidades_execucao'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processos_selecao'))
    )
    op.create_table('afastamentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participante_id', sa.UUID(), nullable=False),
    sa.Column('tipo_afastamento', sa.Enum('LICENCA_MEDICA', 'LICENCA_MATERNIDADE', 'FERIAS', 'LICENCA_CAPACITACAO', 'OUTROS', name='tipoafastamento'), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('registrado_por_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], name=op.f('fk_afastamentos_participante_id_participantes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registrado_por_user_id'], ['users.id'], name=op.f('fk_afastamentos_registrado_por_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_afastamentos'))
    )
    op.create_table('autorizacoes_adicional_noturno',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participante_id', sa.UUID(), nullable=False),
    sa.Column('data_inicio_autorizacao', sa.Date(), nullable=False),
    sa.Column('data_fim_autorizacao', sa.Date(), nullable=True),
    sa.Column('horario_inicio_noturno', sa.Time(), nullable=False),
    sa.Column('horario_fim_noturno', sa.Time(), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('autorizado_por_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autorizado_por_user_id'], ['users.id'], name=op.f('fk_autorizacoes_adicional_noturno_autorizado_por_user_id_users')),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], name=op.f('fk_autorizacoes_adicional_noturno_participante_id_participantes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_autorizacoes_adicional_noturno'))
    )
    op.create_table('convocacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participante_id', sa.UUID(), nullable=False),
    sa.Column('unidade_execucao_id', sa.UUID(), nullable=False),
    sa.Column('chefia_user_id', sa.Integer(), nullable=True),
    sa.Column('canal_comunicacao', sa.String(length=255), nullable=False),
    sa.Column('data_convocacao', sa.Date(), nullable=False),
    sa.Column('data_comparecimento_prevista', sa.Date(), nullable=False),
    sa.Column('horario_comparecimento', sa.String(length=20), nullable=False),
    sa.Column('local_comparecimento', sa.String(length=255), nullable=False),
    sa.Column('periodo_presencial_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_presencial_fim', sa.Date(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('data_comparecimento_efetivo', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'ATENDIDA', 'NAO_ATENDIDA', 'CANCELADA', name='statusconvocacao'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chefia_user_id'], ['users.id'], name=op.f('fk_convocacoes_chefia_user_id_users')),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], name=op.f('fk_convocacoes_participante_id_participantes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unidade_execucao_id'], ['unidades_execucao.id'], name=op.f('fk_convocacoes_unidade_execucao_id_unidades_execucao'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_convocacoes'))
    )
    op.create_table('entregas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_entrega', sa.String(length=50), nullable=False),
    sa.Column('plano_entregas_id', sa.UUID(), nullable=False),
    sa.Column('nome_entrega', sa.String(length=300), nullable=False),
    sa.Column('meta_entrega', sa.Integer(), nullable=False),
    sa.Column('tipo_meta', sa.Enum('UNIDADE', 'PERCENTUAL', name='tipometa'), nullable=False),
    sa.Column('data_entrega', sa.Date(), nullable=False),
    sa.Column('nome_unidade_demandante', sa.String(length=300), nullable=False),
    sa.Column('nome_unidade_destinataria', sa.String(length=300), nullable=False),
    sa.Column('entrega_cancelada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plano_entregas_id'], ['planos_entregas.id'], name=op.f('fk_entregas_plano_entregas_id_planos_entregas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entregas')),
    sa.UniqueConstraint('plano_entregas_id', 'id_entrega', name='uq_entrega_api_key')
    )
    op.create_table('tcrs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participante_id', sa.UUID(), nullable=False),
    sa.Column('chefia_user_id', sa.Integer(), nullable=True),
    sa.Column('modalidade_execucao', sa.Integer(), nullable=False),
    sa.Column('regime_execucao', sa.Enum('INTEGRAL', 'PARCIAL', name='regimeexecucao'), nullable=False),
    sa.Column('prazo_antecedencia_convocacao_dias', sa.Integer(), nullable=False),
    sa.Column('canais_comunicacao', sa.JSON(), nullable=False),
    sa.Column('responsabilidades', sa.Text(), nullable=False),
    sa.Column('ciencia_instalacoes_ergonomia', sa.Boolean(), nullable=False),
    sa.Column('ciencia_nao_direito_adquirido', sa.Boolean(), nullable=False),
    sa.Column('ciencia_custeio_estrutura', sa.Boolean(), nullable=False),
    sa.Column('acoes_melhoria', sa.Text(), nullable=True),
    sa.Column('outras_providencias_inadequado', sa.Text(), nullable=True),
    sa.Column('saldo_banco_horas', sa.Integer(), nullable=True),
    sa.Column('prazo_compensacao_banco_horas', sa.Date(), nullable=True),
    sa.Column('carga_horaria_compensacao', sa.Integer(), nullable=True),
    sa.Column('prazo_compensacao_inexecucao', sa.Date(), nullable=True),
    sa.Column('data_assinatura_participante', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_assinatura_chefia', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'ATIVO', 'SUBSTITUIDO', 'CANCELADO', name='statustcr'), nullable=False),
    sa.Column('tcr_anterior_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chefia_user_id'], ['users.id'], name=op.f('fk_tcrs_chefia_user_id_users')),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], name=op.f('fk_tcrs_participante_id_participantes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tcr_anterior_id'], ['tcrs.id'], name=op.f('fk_tcrs_tcr_anterior_id_tcrs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tcrs'))
    )
    op.create_table('planos_trabalho',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_plano_trabalho', sa.String(length=50), nullable=False),
    sa.Column('origem_unidade', sa.Enum('SIAPE', 'SIORG', name='origemunidade'), nullable=False),
    sa.Column('cod_unidade_autorizadora', sa.BigInteger(), nullable=False),
    sa.Column('cod_unidade_executora', sa.BigInteger(), nullable=False),
    sa.Column('cod_unidade_lotacao_participante', sa.BigInteger(), nullable=False),
    sa.Column('participante_id', sa.UUID(), nullable=False),
    sa.Column('cpf_participante', sa.String(length=11), nullable=False),
    sa.Column('matricula_siape', sa.String(length=7), nullable=False),
    sa.Column('tcr_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_termino', sa.Date(), nullable=False),
    sa.Column('carga_horaria_disponivel', sa.Integer(), nullable=False),
    sa.Column('criterios_avaliacao', sa.Text(), nullable=False),
    sa.Column('declaracao_ausencia_prejuizo_plano', sa.Boolean(), nullable=False),
    sa.Column('declaracao_ausencia_prejuizo_comparecer', sa.Boolean(), nullable=False),
    sa.Column('declaracao_ausencia_prejuizo_contato', sa.Boolean(), nullable=False),
    sa.Column('declaracao_ausencia_prejuizo_sincrono', sa.Boolean(), nullable=False),
    sa.Column('trabalho_noturno', sa.Boolean(), nullable=False),
    sa.Column('plano_entregas_id', sa.UUID(), nullable=True),
    sa.Column('api_sincronizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], name=op.f('fk_planos_trabalho_participante_id_participantes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plano_entregas_id'], ['planos_entregas.id'], name=op.f('fk_planos_trabalho_plano_entregas_id_planos_entregas'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tcr_id'], ['tcrs.id'], name=op.f('fk_planos_trabalho_tcr_id_tcrs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planos_trabalho')),
    sa.UniqueConstraint('origem_unidade', 'cod_unidade_autorizadora', 'id_plano_trabalho', name='uq_plano_trabalho_api_key')
    )
    op.create_table('termos_guarda_equipamento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participante_id', sa.UUID(), nullable=False),
    sa.Column('tcr_id', sa.UUID(), nullable=False),
    sa.Column('descricao_equipamentos', sa.Text(), nullable=False),
    sa.Column('data_autorizacao', sa.Date(), nullable=False),
    sa.Column('autorizado_por_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autorizado_por_user_id'], ['users.id'], name=op.f('fk_termos_guarda_equipamento_autorizado_por_user_id_users')),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], name=op.f('fk_termos_guarda_equipamento_participante_id_participantes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tcr_id'], ['tcrs.id'], name=op.f('fk_termos_guarda_equipamento_tcr_id_tcrs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_termos_guarda_equipamento'))
    )
    op.create_table('avaliacoes_registros_execucao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_periodo_avaliativo', sa.String(length=50), nullable=False),
    sa.Column('plano_trabalho_id', sa.UUID(), nullable=False),
    sa.Column('data_inicio_periodo_avaliativo', sa.Date(), nullable=False),
    sa.Column('data_fim_periodo_avaliativo', sa.Date(), nullable=False),
    sa.Column('descricao_execucao', sa.Text(), nullable=True),
    sa.Column('ocorrencias', sa.Text(), nullable=True),
    sa.Column('data_registro_participante', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avaliacao_registros_execucao', sa.Integer(), nullable=True),
    sa.Column('data_avaliacao_registros_execucao', sa.Date(), nullable=True),
    sa.Column('avaliacao_justificativa', sa.Text(), nullable=True),
    sa.Column('avaliacao_escala_customizada', sa.String(length=100), nullable=True),
    sa.Column('horas_inexecucao', sa.Integer(), nullable=True),
    sa.Column('recurso_texto', sa.Text(), nullable=True),
    sa.Column('recurso_data', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recurso_decisao', sa.Enum('ACATADO', 'NAO_ACATADO', name='decisaorecurso'), nullable=True),
    sa.Column('recurso_decisao_justificativa', sa.Text(), nullable=True),
    sa.Column('recurso_decisao_data', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_recurso', sa.Enum('ABERTO', 'ENCERRADO', name='statusrecurso'), nullable=True),
    sa.ForeignKeyConstraint(['plano_trabalho_id'], ['planos_trabalho.id'], name=op.f('fk_avaliacoes_registros_execucao_plano_trabalho_id_planos_trabalho'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_avaliacoes_registros_execucao')),
    sa.UniqueConstraint('plano_trabalho_id', 'id_periodo_avaliativo', name='uq_avaliacao_periodo')
    )
    op.create_table('contribuicoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_contribuicao', sa.String(length=50), nullable=False),
    sa.Column('rotulo', sa.String(length=50), nullable=True),
    sa.Column('plano_trabalho_id', sa.UUID(), nullable=False),
    sa.Column('tipo_contribuicao', sa.Integer(), nullable=False),
    sa.Column('percentual_contribuicao', sa.Integer(), nullable=False),
    sa.Column('id_plano_entregas', sa.String(length=50), nullable=True),
    sa.Column('id_entrega', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['plano_trabalho_id'], ['planos_trabalho.id'], name=op.f('fk_contribuicoes_plano_trabalho_id_planos_trabalho'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contribuicoes')),
    sa.UniqueConstraint('plano_trabalho_id', 'id_contribuicao', name='uq_contribuicao_api_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contribuicoes')
    op.drop_table('avaliacoes_registros_execucao')
    op.drop_table('termos_guarda_equipamento')
    op.drop_table('planos_trabalho')
    op.drop_table('tcrs')
    op.drop_table('entregas')
    op.drop_table('convocacoes')
    op.drop_table('autorizacoes_adicional_noturno')
    op.drop_table('afastamentos')
    op.drop_table('processos_selecao')
    op.drop_table('planos_entregas')
    op.drop_table('participantes')
    op.drop_table('delegacoes_competencia')
    op.drop_table('unidades_execucao')
    op.drop_table('unidades_instituidoras')
    op.drop_table('notificacoes')
    op.drop_table('atos_autorizacao')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('unidades_autorizadoras')
    op.drop_index(op.f('ix_registros_envio_api_entidade_id'), table_name='registros_envio_api')
    op.drop_table('registros_envio_api')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_table_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_record_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')

    # Enums implicitamente criados pelos CREATE TABLE acima — autogenerate não
    # inclui DROP TYPE no downgrade, então fazemos manualmente.
    for enum_name in (
        "auditaction",
        "competencia",
        "decisaorecurso",
        "motivodesligamento",
        "origemunidade",
        "regimeexecucao",
        "statusato",
        "statusconvocacao",
        "statuspgd",
        "statusrecurso",
        "statustcr",
        "tipoafastamento",
        "tipoentidadesync",
        "tipoevento",
        "tipometa",
        "tipovinculo",
        "userrole",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ###
