"""ai_rewrite_events table

Revision ID: b986b08129ad
Revises: pt_pactuacao_bilateral
Create Date: 2026-05-17 09:55:04.897788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b986b08129ad'
down_revision: Union[str, None] = 'pt_pactuacao_bilateral'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_rewrite_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('registro_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.String(length=20), nullable=False),
    sa.Column('instrucao_custom', sa.Boolean(), nullable=False),
    sa.Column('chars_in', sa.Integer(), nullable=False),
    sa.Column('chars_out', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('parent_event_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_event_id'], ['ai_rewrite_events.id'], name=op.f('fk_ai_rewrite_events_parent_event_id_ai_rewrite_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registro_id'], ['avaliacoes_registros_execucao.id'], name=op.f('fk_ai_rewrite_events_registro_id_avaliacoes_registros_execucao'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_rewrite_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_rewrite_events'))
    )
    op.create_index(op.f('ix_ai_rewrite_events_created_at'), 'ai_rewrite_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_rewrite_events_user_id'), 'ai_rewrite_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_rewrite_events_user_id'), table_name='ai_rewrite_events')
    op.drop_index(op.f('ix_ai_rewrite_events_created_at'), table_name='ai_rewrite_events')
    op.drop_table('ai_rewrite_events')
    # ### end Alembic commands ###
